apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
patches:
  - patch: |
      - op: replace
        path: /spec/interval
        value: 1m
      - op: replace
        path: /spec/prune
        value: true
      - op: add
        path: /spec/retryInterval
        value: 30s
    target:
      kind: Kustomization
      name: flux-system
